[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$ProjectRoot,
    [string]$ProjectName,
    [switch]$SkipPlaywright
)

$reviewerRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$resolvedProject = (Resolve-Path -LiteralPath $ProjectRoot).Path
if (-not (Test-Path -LiteralPath (Join-Path $resolvedProject '.git'))) {
    throw "ProjectRoot is not a Git repository: $resolvedProject"
}
if (-not $ProjectName) { $ProjectName = Split-Path -Leaf $resolvedProject }

$localConfigPath = Join-Path $reviewerRoot 'bridge.local.json'
$existingConfig = $null
if (Test-Path -LiteralPath $localConfigPath -PathType Leaf) {
    $existingConfig = Get-Content -Raw -LiteralPath $localConfigPath | ConvertFrom-Json
    $existingProject = (Resolve-Path -LiteralPath $existingConfig.projectRoot).Path
    if (-not [string]::Equals($existingProject, $resolvedProject, [StringComparison]::OrdinalIgnoreCase)) {
        throw "This reviewer instance is already bound to '$existingProject'. Create a new reviewer instance for '$resolvedProject'."
    }
}

foreach ($command in @('node', 'npm', 'codex', 'claude')) {
    if (-not (Get-Command $command -ErrorAction SilentlyContinue)) {
        throw "Required command '$command' was not found on PATH."
    }
}

function Write-Utf8NoBom {
    param([Parameter(Mandatory = $true)][string]$Path, [Parameter(Mandatory = $true)][string]$Value)
    [System.IO.File]::WriteAllText($Path, $Value + [Environment]::NewLine, [System.Text.UTF8Encoding]::new($false))
}

function ConvertTo-TomlLiteral {
    param([Parameter(Mandatory = $true)][string]$Value)
    return "'" + $Value.Replace("'", "''") + "'"
}

Push-Location $reviewerRoot
try {
    & npm install
    if ($LASTEXITCODE -ne 0) { throw 'npm install failed.' }
    & npm test
    if ($LASTEXITCODE -ne 0) { throw 'Bridge tests failed.' }
} finally {
    Pop-Location
}

$package = Get-Content -Raw -LiteralPath (Join-Path $reviewerRoot 'package.json') | ConvertFrom-Json
$instanceId = if ($existingConfig -and $existingConfig.PSObject.Properties.Name -contains 'instanceId') {
    $existingConfig.instanceId
} else {
    [Guid]::NewGuid().ToString()
}
$configuredAt = if ($existingConfig -and $existingConfig.PSObject.Properties.Name -contains 'configuredAt') {
    $existingConfig.configuredAt
} else {
    [DateTime]::UtcNow.ToString('o')
}
$localConfig = [ordered]@{
    instanceId = $instanceId
    projectName = $ProjectName
    projectRoot = $resolvedProject
    templateVersion = $package.version
    playwrightEnabled = -not [bool]$SkipPlaywright
    configuredAt = $configuredAt
    updatedAt = [DateTime]::UtcNow.ToString('o')
}
Write-Utf8NoBom $localConfigPath ($localConfig | ConvertTo-Json -Depth 5)

$hookScript = Join-Path $reviewerRoot 'dist\claude-hook.js'
$reviewerLeaf = Split-Path -Leaf $reviewerRoot
$claudeSettings = [ordered]@{
    permissions = [ordered]@{
        deny = @(
            "Read($reviewerRoot/**)",
            "Edit($reviewerRoot/**)",
            "Write($reviewerRoot/**)",
            "Glob($reviewerRoot/**)",
            "Grep($reviewerRoot/**)",
            "Bash(*$reviewerLeaf*)",
            "PowerShell(*$reviewerLeaf*)"
        )
    }
    hooks = [ordered]@{
        SessionStart = @(@{ hooks = @(@{ type='command'; command='node'; args=@($hookScript, 'session'); timeout=30; statusMessage='Restoring the paired review session' }) })
        UserPromptSubmit = @(@{ hooks = @(@{ type='command'; command='node'; args=@($hookScript, 'prompt'); timeout=30; statusMessage='Pairing this workstream context with Codex' }) })
        PreToolUse = @(@{ matcher='AskUserQuestion'; hooks = @(@{ type='command'; command='node'; args=@($hookScript, 'question'); timeout=30; statusMessage="Sending Claude's question to the paired Codex adviser" }) })
        Stop = @(@{ hooks = @(@{ type='command'; command='node'; args=@($hookScript, 'stop'); timeout=86400; statusMessage='Waiting for the paired Codex review' }) })
    }
}
Write-Utf8NoBom (Join-Path $reviewerRoot 'claude-bridge.settings.json') ($claudeSettings | ConvertTo-Json -Depth 12)

$mcpServer = ConvertTo-TomlLiteral (Join-Path $reviewerRoot 'dist\mcp-server.js')
$configLines = @(
    '# Generated by Setup-ReviewBridge.ps1. Re-run setup after moving this folder.',
    'default_permissions = "bridge-review"',
    'approval_policy = "on-request"',
    'web_search = "live"',
    'project_doc_fallback_filenames = ["CLAUDE.md"]',
    'project_doc_max_bytes = 65536',
    '',
    '[features]',
    'apps = false',
    'hooks = false',
    '',
    '[mcp_servers.review_bridge]',
    'command = "node"',
    "args = [$mcpServer]",
    'enabled = true',
    'startup_timeout_sec = 10',
    'tool_timeout_sec = 2592000'
)

foreach ($tool in @('set_mode','publish','force_publish','status','cancel')) {
    $configLines += ''
    $configLines += "[mcp_servers.review_bridge.tools.review_bridge_$tool]"
    $configLines += 'approval_mode = "approve"'
}

$configLines += ''
$configLines += '[mcp_servers.review_bridge.tools.review_bridge_write_policy]'
$configLines += 'approval_mode = "prompt"'

if (-not $SkipPlaywright) {
    $playwrightMcp = Join-Path $reviewerRoot 'node_modules\@playwright\mcp\cli.js'
    if (-not (Test-Path -LiteralPath $playwrightMcp)) { throw 'Playwright MCP was not installed.' }
    $playwrightArg = ConvertTo-TomlLiteral $playwrightMcp
    $playwrightOutput = ConvertTo-TomlLiteral (Join-Path $reviewerRoot 'runtime\playwright')
    $playwrightCwd = ConvertTo-TomlLiteral $resolvedProject
    $configLines += @(
        '',
        '[mcp_servers.playwright]',
        'command = "node"',
        "args = [$playwrightArg, '--isolated', '--allow-unrestricted-file-access', '--output-dir', $playwrightOutput]",
        "cwd = $playwrightCwd",
        'enabled = true',
        'startup_timeout_sec = 30',
        'tool_timeout_sec = 120'
    )
    foreach ($tool in @('browser_navigate','browser_fill_form','browser_click','browser_resize','browser_evaluate','browser_run_code_unsafe','browser_press_key')) {
        $configLines += ''
        $configLines += "[mcp_servers.playwright.tools.$tool]"
        $configLines += 'approval_mode = "approve"'
    }
}

$configLines += @(
    '',
    '[permissions.bridge-review]',
    'description = "Independent review: read project files without editing them."',
    'extends = ":read-only"',
    '',
    '[permissions.bridge-write]',
    'description = "Explicit implementation work inside the active project workspace."',
    'extends = ":workspace"'
)
Write-Utf8NoBom (Join-Path $reviewerRoot 'config.toml') ($configLines -join [Environment]::NewLine)

Write-Host "Review bridge installed for '$ProjectName' at $resolvedProject"
Write-Host 'Next: run scripts\Initialize-Reviewer.ps1, then scripts\Start-PolicySetup.ps1.'
